services:
  backend:
    build: ./backend
    container_name: zeus-backend
    ports:
      - "8000:8000"
    
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
      - backend/.env
    environment:
      - DATABASE_URL=sqlite:////data/dev.db
    volumes:
      - ./backend:/app:cached    # keep code bind-mount
      - db-data:/data  # persist DB file
      
  frontend:
    build: ./frontend
    env_file:
      - .env
      - frontend/.env
    
    container_name: zeus-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
   
    #command: npm run dev -- --host 0.0.0.0
    command: ["sh", "-c", "npm rebuild rollup && npm run dev -- --host 0.0.0.0"]

volumes:
  db-data:
